name: otda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip
  - mkl
  - numpy
  - scipy
  - matplotlib
  - numba
  - pyqt>=5.9
  - pandas>=0.18
  - xlrd
  - scikit-learn
  - h5py
  - pillow
  - statsmodels
  - jupyter
  - pytest
  - pytest-cov
  - pytest-mock
  - pytest-timeout
  - joblib
  - psutil
  - flake8
  - spyder
  - numexpr
  - traits>=4.6.0
  - pyface>=6
  - traitsui>=6
  - mne=0.19
  - autograd
  - pot
  - setuptools
  - pip:
    - numpy==1.14.3
    - osqp==0.6.1
    - py==1.9.0
    - pyriemann==0.2.5
    - pytest==6.1.1
    - python-settings==0.2.1
    - scikit-posthocs==0.6.5
    - scs==2.1.2
    - seaborn==0.10.0
    - sphinx-bootstrap-theme==0.7.1
    - sphinx-gallery==0.5.0
    - sqlalchemy==1.3.16
    - statannot==0.2.3
    - toml==0.10.1
    - pymanopt==0.2.3
