name: test_otdapaper
channels:
  - conda-forge
  - defaults
dependencies:
  - alabaster=0.7.12
  - appdirs=1.4.4
  - apptools=5.1.0
  - argh=0.26.2
  - astroid=2.4.2
  - async_generator=1.10
  - atomicwrites=1.4.0
  - attrs=20.3.0
  - autograd=1.3
  - autopep8=1.5.4
  - babel=2.9.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.1
  - bcrypt=3.2.0
  - black=20.8b1
  - blas=1.0
  - bleach=3.2.3
  - blosc=1.21.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2020.12.5
  - cached-property=1.5.1
  - certifi=2020.12.5
  - cffi=1.14.4
  - chardet=4.0.0
  - click=7.1.2
  - cloudpickle=1.6.0
  - colorama=0.4.4
  - configobj=5.0.6
  - cryptography=3.3.1
  - curl=7.71.1
  - cycler=0.10.0
  - dataclasses=0.7
  - decorator=4.4.2
  - defusedxml=0.6.0
  - diff-match-patch=20200713
  - dipy=1.3.0
  - docutils=0.16
  - entrypoints=0.3
  - envisage=4.9.2
  - expat=2.2.9
  - flake8=3.8.4
  - freetype=2.10.4
  - future=0.18.2
  - h5py=3.1.0
  - hdf4=4.2.13
  - hdf5=1.10.6
  - helpdev=0.7.1
  - icc_rt=2019.0.0
  - icu=68.1
  - idna=2.10
  - imageio=2.9.0
  - imagesize=1.2.0
  - importlib-metadata=3.4.0
  - importlib_metadata=3.4.0
  - intel-openmp=2020.3
  - intervaltree=3.0.2
  - ipykernel=5.4.2
  - ipython=7.19.0
  - ipython_genutils=0.2.0
  - isort=5.7.0
  - jedi=0.17.2
  - jinja2=2.11.2
  - joblib=1.0.0
  - jpeg=9d
  - jsoncpp=1.8.4
  - jsonschema=3.2.0
  - jupyter_client=6.1.11
  - jupyter_core=4.7.0
  - jupyterlab_pygments=0.1.2
  - keyring=22.0.1
  - kiwisolver=1.3.1
  - krb5=1.17.2
  - lazy-object-proxy=1.4.3
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=11.0.1
  - libcurl=7.71.1
  - libiconv=1.16
  - liblapack=3.9.0
  - libnetcdf=4.7.4
  - libpng=1.6.37
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libssh2=1.9.0
  - libtiff=4.2.0
  - libxml2=2.9.10
  - lz4-c=1.9.2
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=1.1.1
  - matplotlib=3.3.3
  - matplotlib-base=3.3.3
  - mayavi=4.7.1
  - mccabe=0.6.1
  - mistune=0.8.4
  - mkl=2018.0.3
  - mne=0.19.0
  - mock=4.0.3
  - msys2-conda-epoch=20160418
  - mypy_extensions=0.4.3
  - nbclient=0.5.1
  - nbconvert=6.0.7
  - nbformat=5.1.2
  - nest-asyncio=1.4.3
  - nibabel=3.2.1
  - numexpr=2.7.2
  - numpy=1.19.5
  - numpydoc=1.1.0
  - olefile=0.46
  - openssl=1.1.1i
  - packaging=20.8
  - pandas=1.2.1
  - pandoc=2.11.4
  - pandocfilters=1.4.2
  - paramiko=2.7.2
  - parso=0.7.0
  - pathspec=0.8.1
  - patsy=0.5.1
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.1.0
  - pip=21.0
  - pluggy=0.13.1
  - pot=0.7.0
  - prompt-toolkit=3.0.14
  - psutil=5.8.0
  - ptyprocess=0.7.0
  - pycodestyle=2.6.0
  - pycparser=2.20
  - pydicom=2.1.2
  - pydocstyle=5.1.1
  - pyface=7.1.0
  - pyflakes=2.2.0
  - pygments=2.7.4
  - pylint=2.6.0
  - pyls-black=0.4.6
  - pyls-spyder=0.3.0
  - pynacl=1.4.0
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pyreadline=2.1
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - pysurfer=0.11.0
  - pytables=3.6.1
  - python=3.7.9
  - python-dateutil=2.8.1
  - python-jsonrpc-server=0.4.0
  - python-language-server=0.36.2
  - python_abi=3.7
  - pytz=2020.5
  - pywin32=300
  - pywin32-ctypes=0.2.0
  - pyyaml=5.4.1
  - pyzmq=21.0.1
  - qdarkstyle=2.8.1
  - qt=5.12.9
  - qtawesome=1.0.2
  - qtconsole=5.0.2
  - qtpy=1.9.0
  - regex=2020.11.13
  - requests=2.25.1
  - rope=0.18.0
  - rtree=0.9.7
  - scipy=1.1.0
  - setuptools=49.6.0
  - six=1.15.0
  - snowballstemmer=2.1.0
  - sortedcontainers=2.3.0
  - sphinx=3.4.3
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=1.0.3
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.4
  - sqlite=3.34.0
  - statsmodels=0.11.1
  - tbb=2020.2
  - testpath=0.4.4
  - textdistance=4.2.0
  - threadpoolctl=2.1.0
  - three-merge=0.1.1
  - tk=8.6.10
  - toml=0.10.2
  - tornado=6.1
  - traitlets=5.0.5
  - traits=6.2.0
  - traitsui=7.1.0
  - typed-ast=1.4.2
  - typing_extensions=3.7.4.3
  - ujson=4.0.2
  - urllib3=1.26.3
  - vc=14.2
  - vs2015_runtime=14.28.29325
  - vtk=8.2.0
  - watchdog=1.0.2
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.36.2
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - wrapt=1.11.2
  - xz=5.2.5
  - yaml=0.2.5
  - yapf=0.30.0
  - zeromq=4.3.3
  - zipp=3.4.0
  - zlib=1.2.11
  - zstd=1.4.8
  - pip:
    - pymanopt==0.2.3
    - pyriemann==0.2.6
    - scikit-learn==0.22.2
    - scikit-posthocs==0.6.5
    - seaborn==0.10.0
    - statannot==0.2.3
